### ISSUE TITLE
数据过长OOM 

### ISSUE THREAD

**Issue by liweijieok** [fengzhizi715/saf-logginginterceptor#21]
假如是使用okhttp去下载，也是用了该拦截器，那么很容易就抛出OOM了

下面方法：
`
private fun logLines(lines: Array<String>, hideVerticalLine: Boolean = false,lineLength:Int) = StringBuilder().apply {

            for (line in lines) {
                val length = line.length
                for (i in 0..length / lineLength) {
                    val start = i * lineLength
                    var end = (i + 1) * lineLength
                    end = if (end > line.length) line.length else end

                    if (hideVerticalLine) {
                        append(" " + line.substring(start, end)).append(LINE_SEPARATOR)
                    } else {
                        append("║ " + line.substring(start, end)).append(LINE_SEPARATOR)
                    }
                }
            }
        }.toString()
`
append的时候调用到了底层的Arrays.copyO

抛出

```
java.lang.OutOfMemoryError: Failed to allocate a 159383560 byte allocation with 25165824 free bytes and 68MB until OOM, target footprint 490165608, growth limit 536870912
                                                                                                    	at java.util.Arrays.copyOf(Arrays.java:3257)
                                                                                                    	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
                                                                                                    	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
                                                                                                    	at java.lang.StringBuilder.append(StringBuilder.java:137)
                                                                                                    	at cn.netdiscovery.http.interceptor.Logger$Companion.logLines(Logger.kt:291)
                                                                                                    	at cn.netdiscovery.http.interceptor.Logger$Companion.printJsonResponse(Logger.kt:179)
                                                                                                    	at cn.netdiscovery.http.interceptor.LoggingInterceptor.intercept(LoggingInterceptor.kt:113)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                                                    	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
                                                                                                    	at okhttp3.RealCall.execute(RealCall.java:93)
```

**Comment by liweijieok** [comment]
建议由外部判断是否需要拦截

**Comment by fengzhizi715** [comment]
好的 我这周加一下 @liweijieok

**Comment by fengzhizi715** [comment]
更新了一个版本：v1.6.14
增加了 excludeList ，可以排除某些 path 进行打印日志
看下是否满足需求 @liweijieok

**Comment by liweijieok** [comment]
非常感谢
